# Generated by Django 3.2.13 on 2022-06-09 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=280, unique=True)),
                ('price', models.IntegerField()),
                ('image', models.CharField(max_length=280)),
            ],
        ),
    ]
